New move tutor
ChaChaOrg/ChaChaBot pull request #30
Opened 2021-01-03 20:02 UTC by cdevoe-magus

2021-01-24 19:27 UTC, Talmanaze requested changes
Implement loggin.
Please and thank you <3

2021-01-31 20:54 UTC, natzberg commented on commands/neomovetutor.js
> +							logs.info("[neomovetutro] Displaying results");
typo, neomovetutro -> neomovetutor

2021-01-31 20:57 UTC, natzberg approved these changes
reviewed logging, looks good!

2021-01-31 20:59 UTC, Talmanaze approved these changes

2021-01-31 21:00 UTC, merged